---
# The creation of the cloud-init data is performed locally without root rights.
# So that the data are not written unprotected in the file system, the rights must be restricted.
# Therefore, the currently running deployment user is determined.
- name: Get local user
  ansible.builtin.command: "/usr/bin/id -un"
  changed_when: false
  delegate_to: localhost
  register: whoami_user

- name: Get local group
  ansible.builtin.command: "/usr/bin/id -gn"
  changed_when: false
  delegate_to: localhost
  register: whoami_group

- name: Set_fact - local user
  ansible.builtin.set_fact:
    local_user: "{{ whoami_user.stdout }}"

- name: Set_fact - local group
  ansible.builtin.set_fact:
    local_group: "{{ whoami_group.stdout }}"
...
