---
- name: Create kvm vm instance
  block:
  - name: Install kvm packages
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: true
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    with_items:
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virtinst
      - libvirt-daemon
      - qemu-system-x86
    when: ansible_os_family == 'Debian'
...
